feat: add ESLint playwright plugin
datavisyn/visyn_scripts pull request #106
Opened 2024-11-07 13:08 UTC by oltionchampari

Closes *list issues numbers here*

### Developer Checklist (Definition of Done)

**Issue**

- [ ] All acceptance criteria from the issue are met
- [ ] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
- [ ] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [ ] Descriptive title for this pull request is provided (will be used for release notes later)
- [ ] Reviewer and assignees are defined
- [ ] Add type label (e.g., *bug*, *feature*) to this pull request
- [ ] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [ ] The PR is connected to the corresponding issue (via `Closes #...`)
- [ ] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- this would help us avoid some common mistakes and errors when writing tests

### Screenshots

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

2024-11-07 13:38 UTC, thinkh requested changes
Please move the dependency. Other than that it looks good to me.

2024-11-07 13:38 UTC, thinkh commented on package.json
> +    "eslint-plugin-playwright": "^2.0.1",
I think, you need to move this to the `dependencies` because `devDependencies` are not installed as transitive dependencies. You can see also the other eslint deps above.

2024-11-07 14:13 UTC, oltionchampari commented on package.json
> +    "eslint-plugin-playwright": "^2.0.1",
Thanks, learned something new today :)

2024-11-08 08:50 UTC, thinkh approved these changes
Thanks for integrating my feedback. LGTM.

2024-11-08 08:50 UTC, merged